using MAA.Domain.Sessions;
using Microsoft.EntityFrameworkCore;

namespace MAA.Infrastructure.Data;

/// <summary>
/// Entity Framework Core DbContext for session management.
/// Manages sessions, users, and encryption-related entities.
/// </summary>
public class SessionContext : DbContext
{
    public SessionContext(DbContextOptions<SessionContext> options) : base(options)
    {
    }

    /// <summary>
    /// Sessions: anonymous and authenticated user sessions
    /// </summary>
    public DbSet<Session> Sessions => Set<Session>();

    /// <summary>
    /// Session answers: encrypted/plain wizard responses
    /// </summary>
    public DbSet<SessionAnswer> SessionAnswers => Set<SessionAnswer>();

    /// <summary>
    /// Encryption keys: versioned keys for data encryption
    /// </summary>
    public DbSet<EncryptionKey> EncryptionKeys => Set<EncryptionKey>();

    /// <summary>
    /// Users: registered user accounts (Phase 5)
    /// </summary>
    public DbSet<User> Users => Set<User>();

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        base.OnModelCreating(modelBuilder);

        ConfigureSessionEntity(modelBuilder);
        ConfigureSessionAnswerEntity(modelBuilder);
        ConfigureEncryptionKeyEntity(modelBuilder);
        ConfigureUserEntity(modelBuilder);
    }

    private void ConfigureSessionEntity(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Session>(entity =>
        {
            entity.ToTable("sessions");
            
            entity.HasKey(e => e.Id);
            entity.Property(e => e.Id).ValueGeneratedNever(); // Generated by application
            
            entity.Property(e => e.State)
                .IsRequired()
                .HasConversion<string>() // Store as VARCHAR
                .HasMaxLength(20);
            
            entity.Property(e => e.IpAddress).IsRequired().HasMaxLength(45);
            entity.Property(e => e.UserAgent).IsRequired().HasMaxLength(500);
            entity.Property(e => e.SessionType).IsRequired().HasMaxLength(50).HasDefaultValue("anonymous");
            entity.Property(e => e.EncryptionKeyVersion).IsRequired();
            entity.Property(e => e.Data).IsRequired().HasColumnType("jsonb").HasDefaultValue("{}");
            entity.Property(e => e.ExpiresAt).IsRequired();
            entity.Property(e => e.InactivityTimeoutAt).IsRequired();
            entity.Property(e => e.LastActivityAt).HasDefaultValueSql("NOW()");
            entity.Property(e => e.IsRevoked).HasDefaultValue(false);
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("NOW()");
            entity.Property(e => e.UpdatedAt).HasDefaultValueSql("NOW()");
            entity.Property(e => e.Version).HasDefaultValue(1).IsConcurrencyToken();

            // Indexes
            entity.HasIndex(e => e.UserId).HasFilter("user_id IS NOT NULL");
            entity.HasIndex(e => e.ExpiresAt);
            entity.HasIndex(e => e.Id).IsUnique();

            // Relationships
            entity.HasOne<User>()
                .WithMany()
                .HasForeignKey(e => e.UserId)
                .OnDelete(DeleteBehavior.SetNull);

            entity.HasOne<EncryptionKey>()
                .WithMany()
                .HasForeignKey(e => e.EncryptionKeyVersion)
                .HasPrincipalKey(k => k.KeyVersion)
                .OnDelete(DeleteBehavior.Restrict);
        });
    }

    private void ConfigureSessionAnswerEntity(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<SessionAnswer>(entity =>
        {
            entity.ToTable("session_answers");
            
            entity.HasKey(e => e.Id);
            entity.Property(e => e.Id).ValueGeneratedNever(); // Generated by application
            
            entity.Property(e => e.SessionId).IsRequired();
            entity.Property(e => e.FieldKey).IsRequired().HasMaxLength(200);
            entity.Property(e => e.FieldType).IsRequired().HasMaxLength(50);
            entity.Property(e => e.AnswerPlain).HasMaxLength(1000);
            entity.Property(e => e.AnswerEncrypted).HasColumnType("text");
            entity.Property(e => e.AnswerHash).HasMaxLength(256);
            entity.Property(e => e.KeyVersion).IsRequired();
            entity.Property(e => e.IsPii).HasDefaultValue(false);
            entity.Property(e => e.ValidationErrors).HasColumnType("jsonb");
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("NOW()");
            entity.Property(e => e.UpdatedAt).HasDefaultValueSql("NOW()");
            entity.Property(e => e.Version).HasDefaultValue(1).IsConcurrencyToken();

            // Indexes
            entity.HasIndex(e => e.SessionId);
            entity.HasIndex(e => e.AnswerHash)
                .IsUnique()
                .HasFilter("answer_hash IS NOT NULL");

            // Relationships
            entity.HasOne<Session>()
                .WithMany()
                .HasForeignKey(e => e.SessionId)
                .OnDelete(DeleteBehavior.Cascade);

            entity.HasOne<EncryptionKey>()
                .WithMany()
                .HasForeignKey(e => e.KeyVersion)
                .HasPrincipalKey(k => k.KeyVersion)
                .OnDelete(DeleteBehavior.Restrict);
        });
    }

    private void ConfigureEncryptionKeyEntity(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<EncryptionKey>(entity =>
        {
            entity.ToTable("encryption_keys");
            
            entity.HasKey(e => e.Id);
            entity.Property(e => e.Id).ValueGeneratedNever(); // Generated by application
            
            entity.Property(e => e.KeyVersion).IsRequired();
            entity.Property(e => e.KeyIdVault).IsRequired().HasMaxLength(200);
            entity.Property(e => e.Algorithm).IsRequired().HasMaxLength(50);
            entity.Property(e => e.IsActive).HasDefaultValue(false);
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("NOW()");
            entity.Property(e => e.Metadata).HasColumnType("jsonb");

            // Indexes - unique KeyVersion, only one active key per algorithm
            entity.HasIndex(e => e.KeyVersion).IsUnique();
            entity.HasIndex(e => new { e.Algorithm, e.IsActive })
                .IsUnique()
                .HasFilter("is_active = TRUE");
        });
    }

    private void ConfigureUserEntity(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<User>(entity =>
        {
            entity.ToTable("users");
            
            entity.HasKey(e => e.Id);
            entity.Property(e => e.Id).ValueGeneratedNever(); // Generated by application
            
            entity.Property(e => e.Email).IsRequired().HasMaxLength(320); // RFC 5321 max
            entity.Property(e => e.PasswordHash).IsRequired().HasMaxLength(128);
            entity.Property(e => e.EmailVerified).HasDefaultValue(false);
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("NOW()");
            entity.Property(e => e.UpdatedAt).HasDefaultValueSql("NOW()");
            entity.Property(e => e.Version).HasDefaultValue(1).IsConcurrencyToken();

            // Indexes
            entity.HasIndex(e => e.Email).IsUnique();
        });
    }
}
