using MAA.Domain.Rules;
using MAA.Domain.Sessions;
using Microsoft.EntityFrameworkCore;

namespace MAA.Infrastructure.Data;

/// <summary>
/// Entity Framework Core DbContext for session management.
/// Manages sessions, users, encryption-related entities, and rules engine data.
/// </summary>
public class SessionContext : DbContext
{
    public SessionContext(DbContextOptions<SessionContext> options) : base(options)
    {
    }

    /// <summary>
    /// Sessions: anonymous and authenticated user sessions
    /// </summary>
    public DbSet<Session> Sessions => Set<Session>();

    /// <summary>
    /// Session answers: encrypted/plain wizard responses
    /// </summary>
    public DbSet<SessionAnswer> SessionAnswers => Set<SessionAnswer>();

    /// <summary>
    /// Encryption keys: versioned keys for data encryption
    /// </summary>
    public DbSet<EncryptionKey> EncryptionKeys => Set<EncryptionKey>();

    /// <summary>
    /// Users: registered user accounts (Phase 5)
    /// </summary>
    public DbSet<User> Users => Set<User>();

    /// <summary>
    /// Medicaid Programs: Programs offered by each state (Phase 2)
    /// </summary>
    public DbSet<MedicaidProgram> MedicaidPrograms => Set<MedicaidProgram>();

    /// <summary>
    /// Eligibility Rules: Versioned rules for program eligibility (Phase 2)
    /// </summary>
    public DbSet<EligibilityRule> EligibilityRules => Set<EligibilityRule>();

    /// <summary>
    /// Federal Poverty Levels: Annual FPL thresholds (Phase 2)
    /// </summary>
    public DbSet<FederalPovertyLevel> FederalPovertyLevels => Set<FederalPovertyLevel>();

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        base.OnModelCreating(modelBuilder);

        ConfigureSessionEntity(modelBuilder);
        ConfigureSessionAnswerEntity(modelBuilder);
        ConfigureEncryptionKeyEntity(modelBuilder);
        ConfigureUserEntity(modelBuilder);
        ConfigureMedicaidProgramEntity(modelBuilder);
        ConfigureEligibilityRuleEntity(modelBuilder);
        ConfigureFederalPovertyLevelEntity(modelBuilder);
    }

    private void ConfigureSessionEntity(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Session>(entity =>
        {
            entity.ToTable("sessions");
            
            entity.HasKey(e => e.Id);
            entity.Property(e => e.Id).ValueGeneratedNever(); // Generated by application
            
            entity.Property(e => e.State)
                .IsRequired()
                .HasConversion<string>() // Store as VARCHAR
                .HasMaxLength(20);
            
            entity.Property(e => e.IpAddress).IsRequired().HasMaxLength(45);
            entity.Property(e => e.UserAgent).IsRequired().HasMaxLength(500);
            entity.Property(e => e.SessionType).IsRequired().HasMaxLength(50).HasDefaultValue("anonymous");
            entity.Property(e => e.EncryptionKeyVersion).IsRequired();
            entity.Property(e => e.Data).IsRequired().HasColumnType("jsonb").HasDefaultValue("{}");
            entity.Property(e => e.ExpiresAt).IsRequired();
            entity.Property(e => e.InactivityTimeoutAt).IsRequired();
            entity.Property(e => e.LastActivityAt).HasDefaultValueSql("NOW()");
            entity.Property(e => e.IsRevoked).HasDefaultValue(false);
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("NOW()");
            entity.Property(e => e.UpdatedAt).HasDefaultValueSql("NOW()");
            entity.Property(e => e.Version).HasDefaultValue(1).IsConcurrencyToken();

            // Indexes
            entity.HasIndex(e => e.UserId).HasFilter("user_id IS NOT NULL");
            entity.HasIndex(e => e.ExpiresAt);
            entity.HasIndex(e => e.Id).IsUnique();

            // Relationships
            entity.HasOne<User>()
                .WithMany()
                .HasForeignKey(e => e.UserId)
                .OnDelete(DeleteBehavior.SetNull);

            entity.HasOne<EncryptionKey>()
                .WithMany()
                .HasForeignKey(e => e.EncryptionKeyVersion)
                .HasPrincipalKey(k => k.KeyVersion)
                .OnDelete(DeleteBehavior.Restrict);
        });
    }

    private void ConfigureSessionAnswerEntity(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<SessionAnswer>(entity =>
        {
            entity.ToTable("session_answers");
            
            entity.HasKey(e => e.Id);
            entity.Property(e => e.Id).ValueGeneratedNever(); // Generated by application
            
            entity.Property(e => e.SessionId).IsRequired();
            entity.Property(e => e.FieldKey).IsRequired().HasMaxLength(200);
            entity.Property(e => e.FieldType).IsRequired().HasMaxLength(50);
            entity.Property(e => e.AnswerPlain).HasMaxLength(1000);
            entity.Property(e => e.AnswerEncrypted).HasColumnType("text");
            entity.Property(e => e.AnswerHash).HasMaxLength(256);
            entity.Property(e => e.KeyVersion).IsRequired();
            entity.Property(e => e.IsPii).HasDefaultValue(false);
            entity.Property(e => e.ValidationErrors).HasColumnType("jsonb");
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("NOW()");
            entity.Property(e => e.UpdatedAt).HasDefaultValueSql("NOW()");
            entity.Property(e => e.Version).HasDefaultValue(1).IsConcurrencyToken();

            // Indexes
            entity.HasIndex(e => e.SessionId);
            entity.HasIndex(e => e.AnswerHash)
                .IsUnique()
                .HasFilter("answer_hash IS NOT NULL");

            // Relationships
            entity.HasOne<Session>()
                .WithMany()
                .HasForeignKey(e => e.SessionId)
                .OnDelete(DeleteBehavior.Cascade);

            entity.HasOne<EncryptionKey>()
                .WithMany()
                .HasForeignKey(e => e.KeyVersion)
                .HasPrincipalKey(k => k.KeyVersion)
                .OnDelete(DeleteBehavior.Restrict);
        });
    }

    private void ConfigureEncryptionKeyEntity(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<EncryptionKey>(entity =>
        {
            entity.ToTable("encryption_keys");
            
            entity.HasKey(e => e.Id);
            entity.Property(e => e.Id).ValueGeneratedNever(); // Generated by application
            
            entity.Property(e => e.KeyVersion).IsRequired();
            entity.Property(e => e.KeyIdVault).IsRequired().HasMaxLength(200);
            entity.Property(e => e.Algorithm).IsRequired().HasMaxLength(50);
            entity.Property(e => e.IsActive).HasDefaultValue(false);
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("NOW()");
            entity.Property(e => e.Metadata).HasColumnType("jsonb");

            // Indexes - unique KeyVersion, only one active key per algorithm
            entity.HasIndex(e => e.KeyVersion).IsUnique();
            entity.HasIndex(e => new { e.Algorithm, e.IsActive })
                .IsUnique()
                .HasFilter("is_active = TRUE");
        });
    }

    private void ConfigureUserEntity(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<User>(entity =>
        {
            entity.ToTable("users");
            
            entity.HasKey(e => e.Id);
            entity.Property(e => e.Id).ValueGeneratedNever(); // Generated by application
            
            entity.Property(e => e.Email).IsRequired().HasMaxLength(320); // RFC 5321 max
            entity.Property(e => e.PasswordHash).IsRequired().HasMaxLength(128);
            entity.Property(e => e.EmailVerified).HasDefaultValue(false);
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("NOW()");
            entity.Property(e => e.UpdatedAt).HasDefaultValueSql("NOW()");
            entity.Property(e => e.Version).HasDefaultValue(1).IsConcurrencyToken();

            // Indexes
            entity.HasIndex(e => e.Email).IsUnique();
        });
    }

    private void ConfigureMedicaidProgramEntity(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<MedicaidProgram>(entity =>
        {
            entity.ToTable("medicaid_programs");
            
            entity.HasKey(e => e.ProgramId);
            entity.Property(e => e.ProgramId).ValueGeneratedNever(); // Generated by application
            
            entity.Property(e => e.StateCode).IsRequired().HasMaxLength(2);
            entity.Property(e => e.ProgramName).IsRequired().HasMaxLength(100);
            entity.Property(e => e.ProgramCode).IsRequired().HasMaxLength(20);
            entity.Property(e => e.EligibilityPathway).IsRequired().HasConversion<string>().HasMaxLength(50);
            entity.Property(e => e.Description).HasColumnType("text");
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("NOW()");
            entity.Property(e => e.UpdatedAt).HasDefaultValueSql("NOW()");

            // Unique constraints
            entity.HasIndex(e => e.ProgramCode).IsUnique();
            entity.HasIndex(e => new { e.StateCode, e.ProgramName }).IsUnique();
            
            // Query optimization indexes
            entity.HasIndex(e => new { e.StateCode, e.EligibilityPathway });
            
            // Relationships
            entity.HasMany(e => e.Rules)
                .WithOne(r => r.Program)
                .HasForeignKey(r => r.ProgramId)
                .OnDelete(DeleteBehavior.Cascade);
        });
    }

    private void ConfigureEligibilityRuleEntity(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<EligibilityRule>(entity =>
        {
            entity.ToTable("eligibility_rules");
            
            entity.HasKey(e => e.RuleId);
            entity.Property(e => e.RuleId).ValueGeneratedNever(); // Generated by application
            
            entity.Property(e => e.ProgramId).IsRequired();
            entity.Property(e => e.StateCode).IsRequired().HasMaxLength(2);
            entity.Property(e => e.RuleName).IsRequired().HasMaxLength(100);
            entity.Property(e => e.Version).IsRequired().HasColumnType("numeric(4,2)");
            entity.Property(e => e.RuleLogic).IsRequired().HasColumnType("jsonb");
            entity.Property(e => e.EffectiveDate).IsRequired().HasColumnType("date");
            entity.Property(e => e.EndDate).HasColumnType("date");
            entity.Property(e => e.CreatedBy);
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("NOW()");
            entity.Property(e => e.UpdatedAt).HasDefaultValueSql("NOW()");
            entity.Property(e => e.Description).HasColumnType("text");

            // Unique constraints
            entity.HasIndex(e => new { e.ProgramId, e.Version }).IsUnique();
            
            // Query optimization indexes
            entity.HasIndex(e => new { e.ProgramId, e.EffectiveDate, e.EndDate });
            entity.HasIndex(e => new { e.StateCode, e.EffectiveDate });
            
            // Relationships
            entity.HasOne(e => e.Program)
                .WithMany(p => p.Rules)
                .HasForeignKey(e => e.ProgramId)
                .OnDelete(DeleteBehavior.Cascade);
        });
    }

    private void ConfigureFederalPovertyLevelEntity(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<FederalPovertyLevel>(entity =>
        {
            entity.ToTable("federal_poverty_levels");
            
            entity.HasKey(e => e.FplId);
            entity.Property(e => e.FplId).ValueGeneratedNever(); // Generated by application
            
            entity.Property(e => e.Year).IsRequired();
            entity.Property(e => e.HouseholdSize).IsRequired();
            entity.Property(e => e.AnnualIncomeCents).IsRequired();
            entity.Property(e => e.StateCode).HasMaxLength(2);
            entity.Property(e => e.AdjustmentMultiplier).HasColumnType("numeric(3,2)");
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("NOW()");
            entity.Property(e => e.UpdatedAt).HasDefaultValueSql("NOW()");

            // Unique constraint for (year, household_size, state_code)
            entity.HasIndex(e => new { e.Year, e.HouseholdSize, e.StateCode }).IsUnique();
            
            // Query optimization indexes
            entity.HasIndex(e => new { e.Year, e.HouseholdSize });
        });
    }}