// <auto-generated />
using System;
using MAA.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MAA.Infrastructure.Migrations
{
    [DbContext(typeof(SessionContext))]
    [Migration("20260209100002_SeedPilotStateRules")]
    partial class SeedPilotStateRules
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            // MedicaidProgram entity configuration (same as InitializeRulesEngine)
            modelBuilder.Entity("MAA.Domain.Rules.MedicaidProgram", b =>
                {
                    b.Property<Guid>("ProgramId")
                        .HasColumnType("uuid")
                        .HasColumnName("program_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("EligibilityPathway")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("eligibility_pathway");

                    b.Property<string>("ProgramCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("program_code");

                    b.Property<string>("ProgramName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("program_name");

                    b.Property<string>("StateCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("state_code");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("ProgramId");

                    b.HasIndex("ProgramCode")
                        .IsUnique();

                    b.HasIndex("StateCode", "ProgramName")
                        .IsUnique();

                    b.HasIndex("StateCode", "EligibilityPathway");

                    b.ToTable("medicaid_programs", (string)null);
                });

            // EligibilityRule entity configuration
            modelBuilder.Entity("MAA.Domain.Rules.EligibilityRule", b =>
                {
                    b.Property<Guid>("RuleId")
                        .HasColumnType("uuid")
                        .HasColumnName("rule_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<DateTime>("EffectiveDate")
                        .HasColumnType("date")
                        .HasColumnName("effective_date");

                    b.Property<Guid>("ProgramId")
                        .HasColumnType("uuid")
                        .HasColumnName("program_id");

                    b.Property<string>("RuleLogic")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("rule_logic");

                    b.Property<string>("RuleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("rule_name");

                    b.Property<string>("StateCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("state_code");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<decimal>("Version")
                        .HasColumnType("numeric(4,2)")
                        .HasColumnName("version");

                    b.HasKey("RuleId");

                    b.HasIndex("ProgramId", "Version")
                        .IsUnique();

                    b.HasIndex("ProgramId", "EffectiveDate", "EndDate");

                    b.HasIndex("StateCode", "EffectiveDate");

                    b.ToTable("eligibility_rules", (string)null);
                });

            // FederalPovertyLevel entity configuration
            modelBuilder.Entity("MAA.Domain.Rules.FederalPovertyLevel", b =>
                {
                    b.Property<Guid>("FplId")
                        .HasColumnType("uuid")
                        .HasColumnName("fpl_id");

                    b.Property<decimal?>("AdjustmentMultiplier")
                        .HasColumnType("numeric(3,2)")
                        .HasColumnName("adjustment_multiplier");

                    b.Property<long>("AnnualIncomeCents")
                        .HasColumnType("bigint")
                        .HasColumnName("annual_income_cents");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("HouseholdSize")
                        .HasColumnType("integer")
                        .HasColumnName("household_size");

                    b.Property<string>("StateCode")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("state_code");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("FplId");

                    b.HasIndex("Year", "HouseholdSize", "StateCode")
                        .IsUnique();

                    b.HasIndex("Year", "HouseholdSize");

                    b.ToTable("federal_poverty_levels", (string)null);
                });

            modelBuilder.Entity("MAA.Domain.Rules.EligibilityRule", b =>
                {
                    b.HasOne("MAA.Domain.Rules.MedicaidProgram", "Program")
                        .WithMany("Rules")
                        .HasForeignKey("ProgramId")
                        .IsRequired()
                        .HasConstraintName("FK_eligibility_rules_medicaid_programs_program_id");

                    b.Navigation("Program");
                });

            modelBuilder.Entity("MAA.Domain.Rules.MedicaidProgram", b =>
                {
                    b.Navigation("Rules");
                });
#pragma warning restore 612, 618
        }
    }
}
