using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace MAA.Infrastructure.StateContext;

/// <summary>
/// Entity Framework Core configuration for StateContext entity
/// </summary>
public class StateContextConfiguration : IEntityTypeConfiguration<Domain.StateContext.StateContext>
{
    public void Configure(EntityTypeBuilder<Domain.StateContext.StateContext> builder)
    {
        builder.ToTable("state_contexts");

        // Primary key
        builder.HasKey(e => e.Id);
        builder.Property(e => e.Id).ValueGeneratedNever(); // Generated by application

        // Properties
        builder.Property(e => e.SessionId)
            .IsRequired()
            .HasColumnName("session_id");

        builder.Property(e => e.StateCode)
            .IsRequired()
            .HasMaxLength(2)
            .HasColumnName("state_code");

        builder.Property(e => e.StateName)
            .IsRequired()
            .HasMaxLength(50)
            .HasColumnName("state_name");

        builder.Property(e => e.ZipCode)
            .IsRequired()
            .HasMaxLength(5)
            .HasColumnName("zip_code");

        builder.Property(e => e.IsManualOverride)
            .IsRequired()
            .HasDefaultValue(false)
            .HasColumnName("is_manual_override");

        builder.Property(e => e.EffectiveDate)
            .IsRequired()
            .HasColumnName("effective_date");

        builder.Property(e => e.CreatedAt)
            .IsRequired()
            .HasDefaultValueSql("NOW()")
            .HasColumnName("created_at");

        builder.Property(e => e.UpdatedAt)
            .IsRequired(false)
            .HasColumnName("updated_at");

        // Indexes
        builder.HasIndex(e => e.SessionId)
            .HasDatabaseName("IX_StateContexts_SessionId")
            .IsUnique(); // One state context per session

        builder.HasIndex(e => e.StateCode)
            .HasDatabaseName("IX_StateContexts_StateCode");

        // Relationships
        builder.HasOne(sc => sc.Session)
            .WithOne() // Assuming Session doesn't have StateContext navigation property yet
            .HasForeignKey<Domain.StateContext.StateContext>(sc => sc.SessionId)
            .OnDelete(DeleteBehavior.Cascade);

        builder.HasOne(sc => sc.StateConfiguration)
            .WithMany(config => config.StateContexts)
            .HasForeignKey(sc => sc.StateCode)
            .HasPrincipalKey(config => config.StateCode)
            .OnDelete(DeleteBehavior.Restrict);
    }
}
